apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260613-190213-u8mdkdb5sk2c-service
spec:
  selector:
    app: enterprise-system-20260613-190213-u8mdkdb5sk2c
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
